<?php

declare(strict_types=1);

namespace App\Managing\Service\Admin;

/**
 * Table and identity SQL for the temporary Attaching identifier migration.
 */
final readonly class AttachmentIdentifierMigrationSchemaSql
{
    public function createAttachmentTable(): string
    {
        return <<<'SQL'
            CREATE TABLE attachment (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                type varchar(255) NOT NULL,
                media_kind varchar(255) DEFAULT NULL,
                document_kind varchar(255) DEFAULT NULL,
                storage_kind varchar(255) NOT NULL,
                visibility varchar(255) NOT NULL,
                status varchar(255) NOT NULL,
                original_name varchar(255) NOT NULL,
                stored_name varchar(255) NOT NULL,
                extension varchar(32) DEFAULT NULL,
                mime_type varchar(191) NOT NULL,
                size integer NOT NULL,
                checksum varchar(128) NOT NULL,
                storage_path varchar(1024) NOT NULL,
                title varchar(255) DEFAULT NULL,
                description text DEFAULT NULL,
                alt_text text DEFAULT NULL,
                width integer DEFAULT NULL,
                height integer DEFAULT NULL,
                duration_ms integer DEFAULT NULL,
                page_count integer DEFAULT NULL,
                created_at timestamp(0) without time zone NOT NULL,
                updated_at timestamp(0) without time zone NOT NULL,
                deleted_at timestamp(0) without time zone DEFAULT NULL
            )
            SQL;
    }

    public function createAttachmentLinkTable(): string
    {
        return <<<'SQL'
            CREATE TABLE attachment_link (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                attachment_id integer NOT NULL,
                owner_type varchar(191) NOT NULL,
                owner_id varchar(191) NOT NULL,
                context varchar(191) DEFAULT NULL,
                slot varchar(191) DEFAULT NULL,
                position integer NOT NULL,
                is_primary boolean NOT NULL,
                created_at timestamp(0) without time zone NOT NULL,
                updated_at timestamp(0) without time zone NOT NULL,
                CONSTRAINT fk_attachment_link_attachment FOREIGN KEY (attachment_id) REFERENCES attachment (id) ON DELETE CASCADE
            )
            SQL;
    }

    public function reseedAttachmentIdentity(): string
    {
        return <<<'SQL'
            SELECT setval(pg_get_serial_sequence('attachment', 'id'), (SELECT COALESCE(MAX(id), 0) FROM attachment), true)
            SQL;
    }

    public function reseedAttachmentLinkIdentity(): string
    {
        return <<<'SQL'
            SELECT setval(pg_get_serial_sequence('attachment_link', 'id'), (SELECT COALESCE(MAX(id), 0) FROM attachment_link), true)
            SQL;
    }
}
